### ISSUE TITLE
Issue running the tests

### ISSUE THREAD

**Issue by epinault** [chulkilee/ex_force#11]
I just pulled master and one of the test is not passing

mix test
..........

  1) test get with load_from_system_env: success (ExForce.AuthTest)
     test/ex_force/auth_test.exs:60
     env vars are not set for test; see env.global section of .travis.yml
     code: assert System.get_env("SALESFORCE_ENDPOINT") == "http://127.0.0.1:1234",
     stacktrace:
       test/ex_force/auth_test.exs:61: (test)

................................

**Comment by chulkilee** [comment]
As the message says, the test case requires env variables, which have example values in `.travis.yml`.

```sh
# values from .travis.yml
SALESFORCE_ENDPOINT=http://127.0.0.1:1234 \
SALESFORCE_CLIENT_ID=client_id_env \
SALESFORCE_CLIENT_SECRET=client_secret_env \
SALESFORCE_USERNAME=username_env \
SALESFORCE_PASSWORD=password_env \
SALESFORCE_SECURITY_TOKEN=security_token_env \
SALESFORCE_API_VERSION=api_version_env \
  mix test
```

I don't know how to inject env vars during test run with elixir. I may introduce a wrapper script to do it.

**Comment by dustinfarris** [comment]
You could, in test_helper.exs:

```exs
System.put_env("SALESFORCE_ENDPOINT", "http://127.0.0.1.1234")
```

although the wrapper script would be more true to actual usage.

**Comment by chulkilee** [comment]
Great! 4bcd9afb7c0fbdc45073508de7c533dffa72e2d5 fixed this :)
