### ISSUE TITLE
Missing headers information

### ISSUE THREAD

**Issue by epinault** [chulkilee/ex_force#13]
I need the headers as part of the response. So far only the status and the body are passed. There are many reason why someone would want the headers

1) So per Salesforce doc  https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_rest_conditional_requests.htm?search_text=etag

This is needed to make use of the version/revision of an object and detect conflicts

2) The API quota limit are return along the request in the headers per doc
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers_api_usage.htm?search_text=limit

I tried just adding the header as such

  defp transform_response(%Response{body: body, status_code: status, headers: headers}), do: {status, body, headers}

This would work beside the number of test to fix 😅 . What do you think?

**Comment by epinault** [comment]
So for the etag, I am less interested since they apparently limit to Account object... this is in the tiny prints of their docs...  But definitely the limit is needed for me.

**Comment by chulkilee** [comment]
I see the use case and agree that there should be a way to get the headers as well.

What about returning general response struct (like `HTTPoison.Response`) instead of tuple?

**Comment by epinault** [comment]
yea, that works great I think for now. At least it is easy to lookup what it is

**Comment by chulkilee** [comment]
@epinault could you test out #16?

**Comment by epinault** [comment]
nice! yes, let me try that

**Comment by epinault** [comment]
Looks good to me and works good too. I think you can merge it in master
