### ISSUE TITLE
Insert / Upsert Functionality

### ISSUE THREAD

**Issue by MrDoops** [chulkilee/ex_force#19]
@chulkilee 
Did you have a plan for adding Insert or Upsert functionality with this API client?

I'm spending some time building an API client in Tesla for an application who's data I'll be persisting to Salesforce. The Tesla client is moving along nicely, but I'm still looking for a good way to insert and update Salesforce records from Elixir.

The quick fix would be to implement the insert functionality in your library using HTTPoison 0.13, but if the time to implement the whole library in #17 Tesla is approachable, I'd be willing to invest time towards that end as well.

**Comment by chulkilee** [comment]
Hi - I actually has WIP branch for #17 - just pushed it and opened #21. Please feel free to take a look.
