### ISSUE TITLE
Release 0.2.2

### ISSUE THREAD

**Issue by jeroenvisser101** [chulkilee/ex_force#29]
Hi! Would you be able to release a new version that includes #27?

**Comment by chulkilee** [comment]
Done - pushed to hex as well

- https://github.com/chulkilee/ex_force/releases/tag/v0.2.2
- https://github.com/chulkilee/ex_force/commit/9583aba1f292400189d4de1639064ad89504c0ac

**Comment by jeroenvisser101** [comment]
Thanks!
