### ISSUE TITLE
Please Include password+token in password field example.

### ISSUE THREAD

**Issue by GenericJam** [chulkilee/ex_force#37]
Thank you so much for this library.

Could you please include in your usage documentation that password needs to be password+token? 

I was struggling with trying to get the library working for hours when I finally stumbled on this - https://developer.salesforce.com/forums/?id=906F000000099liIAA - combined with some other same JS code where I realized I needed cat password+token.

**Comment by chulkilee** [comment]
Good catch! Thanks for the report.

The [linked salesforce doc](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_username_password_oauth_flow.htm) actually mentions that btw.

> You must append the user’s security token to their password A security token is an automatically-generated key from Salesforce. For example, if a user's password is mypassword, and their security token is XXXXXXXXXX, then the value provided for this parmeter must be mypasswordXXXXXXXXXX. For more information on security tokens see “Reset Your Security Token” in the online help.

I believe security token is not needed when when the requesting ip address is trusted: see [Reset Your Security Token](https://help.salesforce.com/articleView?id=user_security_token.htm&type=5)

> When you access Salesforce from an IP address that’s outside your company’s trusted IP range using a desktop client or the API, you need a security token to log in

**Comment by GenericJam** [comment]
Hi Chulkilee,

Thanks for addressing that quickly. One more thing - it would be helpful if
you included a link in your github readme to the hex documentation page.
Otherwise, people have to independently find them through Google, etc.

All the best,
Kevin

**Comment by chulkilee** [comment]
> Thanks for addressing that quickly. One more thing - it would be helpful if
you included a link in your github readme to the hex documentation page.
Otherwise, people have to independently find them through Google, etc.

Done at 467de59c53130eb9c3703ab8ea2282e0b1884b4c - the hexdoc will be updated at the next release. Thanks for the suggestion!
