### ISSUE TITLE
Publish new patch version to Hex with OTP 24 compatibility

### ISSUE THREAD

**Issue by Dacello** [chulkilee/ex_force#59]
With the merge of https://github.com/chulkilee/ex_force/pull/55, this is now compatible with erlang OTP 24, however there is still not a new version published to hex for this. Figured I'd go ahead and create this issue to move that along.

**Comment by chulkilee** [comment]
Here you go!

https://hex.pm/packages/ex_force/0.4.1

(I missed the change log entry for #55 / #56   🤦 )

**Comment by Dacello** [comment]
Thank you @chulkilee !
